### ISSUE TITLE
wrap and down redis

### ISSUE THREAD

**Issue by mogadanez** [BryanDonovan/node-cache-manager#159]
If Redis not available - should it just execute wrapped command? 
now it failed: 

```
AbortError: GET can't be processed. The connection is already closed.
    at handle_offline_command (/api/node_modules/redis/index.js:779:15)
    at RedisClient.internal_send_command (/api/node_modules/redis/index.js:813:9)
    at RedisClient.get (/api/node_modules/redis/lib/commands.js:46:25)
    at /api/node_modules/cache-manager-redis-store/dist/index.js:118:20
    at new Promise (<anonymous>)
    at Object.get (/api/node_modules/cache-manager-redis-store/dist/index.js:107:14)
    at Object.self.wrap (/api/node_modules/cache-manager/lib/caching.js:184:20)
    at /api/node_modules/cache-manager/lib/caching.js:52:18
    at new Promise (<anonymous>)
    at Object.wrapPromise (/api/node_modules/cache-manager/lib/caching.js:51:16)
    at Object.self.wrap (/api/node_modules/cache-manager/lib/caching.js:168:32)
    ```

**Comment by kraiz** [comment]
You should be able to set `ignoreCacheErrors ` as option of `caching()` to `true` to get this behaviour.

I just found that inside the codebase:
https://github.com/BryanDonovan/node-cache-manager/blob/b3aa1d59885d5a011fd02f8c197c78f4f6235dde/lib/caching.js#L32

**Comment by mogadanez** [comment]
its also **required** to set  `enable_offline_queue:false` for redis instance
otherwise redis try to handle failures self and never call callback

https://github.com/BryanDonovan/node-cache-manager/issues/51
