### ISSUE TITLE
Error Express Engine Cached manager

### ISSUE THREAD

**Issue by jhimelymendoza** [BryanDonovan/node-cache-manager#165]
I am working with angular universal and I am caching the most used requests. I have this implementation that works for me with angular universal 9, but I am migrating the project to 12, I took the same implementation and it throws me this error.

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:154:9)
    at CrittersExtended.getCssAsset (C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:133014:31)
    at CrittersExtended.embedLinkedStylesheet (C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:133094:37)
    at C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:132943:79
    at Array.map (<anonymous>)
    at C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:132943:61
    at CrittersExtended.process (C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:132945:8)
    at InlineCriticalCssProcessor.<anonymous> (C:\Users\Usuario\Documents\work\fibertel\ux-figma\fc-ecommerce-Front-Clientes\dist\fc-ecommerce-Front-Clientes\server\main.js:133438:44)
    at Generator.next (<anonymous>)
`.
this is the implementation
[express-engine.txt](https://github.com/BryanDonovan/node-cache-manager/files/7128891/express-engine.txt)

**Comment by BryanDonovan** [comment]
I might be missing something, but it doesn't look like your error is related to `cache-manager`.
